---
    - name: Install java jdk
      yum:
        name: java-11*
        state: present
      when: ansible_distribution == "Amazon"


    - name: Install java jdk
      apt: 
        name: openjdk-17-jdk
        state: present
      when: ansible_distribution == "Ubuntu"
    

...
