CREATE DATABASE IF NOT EXISTS syslogs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE syslogs;

CREATE TABLE IF NOT EXISTS stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    cpu_usage FLOAT NOT NULL,
    memory_usage FLOAT NOT NULL
);
