---
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: This command will change the working directory to somedir/
      shell:
        cmd: wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.11-1_all.deb
    
    - name: Install MySQL client, MySQL community server, and MySQL server version 8.0.32
      shell: |
        sudo apt update
        sudo apt install -y mysql-client=8.0.32 mysql-community-server=8.0.32 mysql-server=8.0.32

    - name: Check the status of MySQL service
      shell: |
        systemctl status mysql | grep "Active:"
      register: mysql_status
      ignore_errors: yes
...