---

    - name: Ensure MySQL configuration allows remote connections
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Restart MySQL service
      systemd:
        name: mysql
        state: restarted
        enabled: yes
...
...