---
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start and Enable MySQL Service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Install PyMySQL for Python 3.x
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes
   
    - name: Create MySQL Table
      mysql_query:
        login_user: root
        query: |
          CREATE TABLE IF NOT EXISTS system_stats.stats (
            id INT AUTO_INCREMENT PRIMARY KEY,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            cpu_usage FLOAT,
            memory_usage FLOAT
          );
      ignore_errors: yes

    - name: Create MySQL User
      mysql_user:
        name: monitor
        password: password123
        priv: "system_stats.*:ALL"
        host: "%"
        state: present

    - name: Allow Remote Connections
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*=\s*127.0.0.1'
        replace: 'bind-address = 0.0.0.0'

    - name: Restart MySQL Service
      systemd:
        name: mysql
        state: restarted
...