---
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start and Enable MySQL Service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Install PyMySQL for Python 3.x
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Change MySQL root authentication to password-based
      shell: |
        mysql -u root <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RootPassword123';
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash

    - name: Create a MySQL database and user
      shell: |
        mysql -u root -pRootPassword123 <<EOF
        CREATE DATABASE system_stats;
        CREATE USER 'monitor'@'%' IDENTIFIED BY 'password123';
        GRANT ALL PRIVILEGES ON system_stats.* TO 'monitor'@'%';
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash

    - name: Update MySQL config to allow remote access
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Restart MySQL service
      systemd:
        name: mysql
        state: restarted
        enabled: yes
...
