---
- name: Create MySQL database
  mysql_db:
    name: syslogs
    state: present
    login_user: devops
    login_password: "{{ mysql_devops_password }}"
    
- name: add sample data to database  
  copy: 
    src: init_db.sql 
    dest: /tmp/init_db.sql  
     
- name: insert sample data into database  
  mysql_db: 
    name: syslogs 
    state: import 
    target: /tmp/init_db.sql 
    login_user: devops 
    login_password: "{{ mysql_devops_password }}"

...