---
- name: Copy SQL file to MySQL server
  copy:
    src: init_db.sql
    dest: /tmp/init_db.sql
    owner: root
    group: root
    mode: '0644'

- name: Read SQL file content
  slurp:
    src: /tmp/init_db.sql
  register: sql_file_content

- name: Run SQL script to create table
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    query: "{{ sql_file_content['content'] | b64decode }}"
  become: yes
...

