---
- name: Create MySQL database
  mysql_db:
    name: syslogs
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    login_user: root
    login_password: "{{ mysql_root_password }}"



...