---
- name: Create MySQL database
  mysql_db:
    name: syslogs
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL table
  mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: syslogs
    query: |
      CREATE TABLE IF NOT EXISTS stats (
          id INT AUTO_INCREMENT PRIMARY KEY,
          timestamp DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
          cpu_usage FLOAT NOT NULL,
          memory_usage FLOAT NOT NULL
      );
...