---
- name: Install httpd on all servers
  hosts: mysql
  become: yes
  tasks:
    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Deploy Python script
      copy:
        src: system_stats.py
        dest: /opt/system_stats.py
        mode: '0755'

    - name: Schedule with cron
      cron:
        name: "Run system stats script"
        job: "/usr/bin/python3 /opt/system_stats.py >> /var/log/system_stats.log 2>&1"
        minute: "*/5"
...
