---
- name: Install my sql on  SQL server
  hosts: mysql
  become: yes
  tasks:
    - name: Update server
      apt:
        update_cache: yes

    - name: Install mysql
      apt:
        name: mysql-server
        state: present
   
    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Ensure MySQL service is enabled on boot
      service:
        name: mysql
        enabled: yes

    - name: Set root password
      mysql_user:
        name: root
        host: localhost
        password: "Admin"
        state: present

    - name: Create a database
      mysql_db:
        name: my_database
        state: present

    - name: Create a user
      mysql_user:
        name: my_user
        host: localhost
        password: "{{ my_user_password }}"
        priv: 'my_database.*:ALL'
        state: present

...
