---
- name: Install my sql on  SQL server
  hosts: mysql
  become: yes
  tasks:
    - name: Update server
      apt:
        update_cache: yes

    - name: Install mysql
      apt:
        name: mysql-server
        state: present
   
    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Ensure MySQL service is enabled on boot
      service:
        name: mysql
        enabled: yes

...
