---
- name: Install my sql on  SQL server
  hosts: mysql
  become: yes
  tasks:
    - name: Update server
      apt:
        update_cache: yes

    - name: Install mysql
      apt:
        name: mysql-server
        state: present
   
    - name: Enable mysql
      shell:
        cmd: systemctl enable --now mysql
        
...
