---
- name: Setup MySQL Database for System Monitoring
  hosts: mysql_server
  become: yes
  vars:
    mysql_root_password: "your-root-password"
    monitoring_db: "system_monitor"
    monitoring_user: "monitoring_user"
    monitoring_password: "monitoring_password"

  tasks:
    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install MySQL client package (Ubuntu/Debian)
      apt:
        name: mysql-client
        state: present
        update_cache: yes

    - name: Create MySQL Database
      community.mysql.mysql_db:
        name: "{{ monitoring_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL User
      community.mysql.mysql_user:
        name: "{{ monitoring_user }}"
        password: "{{ monitoring_password }}"
        priv: "{{ monitoring_db }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create system_stats table
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        db: "{{ monitoring_db }}"
        query: |
          CREATE TABLE IF NOT EXISTS system_stats (
              id INT AUTO_INCREMENT PRIMARY KEY,
              hostname VARCHAR(255),
              cpu_usage FLOAT,
              memory_usage FLOAT,
              timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
