---

    - name: Install cronie (CentOS)
      yum:
        name: cronie
        state: present
      when: ansible_os_family == "RedHat" or ansible_os_family == "Amazon" or ansible_os_family == "Fedora"

    - name: Ensure crond service is running (CentOS)
      service:
        name: crond
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat" or ansible_os_family == "Amazon" or ansible_os_family == "Fedora"
...