# tasks file for python
---
      - name: Gather facts about the system
        setup:
          gather_subset: "!all,!min,distribution"

      - name: Install Python (Amazon Linux/RHEL)
        yum:
          name: python3
          state: present
        when: ansible_facts['distribution'] in ['Amazon', 'RedHat', 'CentOS']

      - name: Install Python (Ubuntu/Debian)
        apt:
          name: python3
          state: present
          update_cache: yes
        when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

      - name: Install Python pip (Amazon Linux/RHEL)
        yum:
          name: python3-pip
          state: present
        when: ansible_facts['distribution'] in ['Amazon', 'RedHat', 'CentOS']

      - name: Install Python pip (Ubuntu/Debian)
        apt:
          name: python3-pip
          state: present
        when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

      - name: Install psutil and mysql-connector-python packages
        pip:
          name:
            - psutil==5.9.0
            - mysql-connector-python==8.0.32
          executable: /usr/bin/pip3

      - name: Install MySQL client (Amazon Linux/RHEL)
        yum:
          name: mariadb105
          state: present
        when: ansible_facts['distribution'] in ['Amazon', 'RedHat', 'CentOS']

      - name: Install MySQL client (Ubuntu/Debian)
        apt:
          name: mariadb-client
          state: present
        when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']
...