---
# tasks file for python

- name: Install Python
  yum:
    name: python3
    state: present

- name: Install Python
  yum:
    name: python3-pip
    state: present

- name: Install psutil-5.9.0 and mysql-connector-python==8.0.32
  shell:
    cmd: /usr/bin/python3 -m pip install psutil==5.9.0 mysql-connector-python==8.0.32 --force-reinstall

...